name: euler-haskell
version: 0.1.0.0
github: neillrobson/euler-haskell
author: Neill Robson
maintainer: neill@neillrobson.com
license: BSD-3-Clause
copyright: 2026 - Present
extra-source-files: README.md

description: Please see the README on GitHub at
  <https://github.com/neillrobson/euler-haskell#readme>

dependencies:
  - array
  - base >=4.7 && <5
  - containers
  - directory
  - template-haskell

ghc-options:
  - -Wall

default-extensions:
  - DataKinds

library:
  source-dirs: src

executables:
  euler:
    source-dirs: app
    main: Main.hs
    dependencies:
      - euler-haskell
    ghc-options:
      - -O2
